version: "3.9"
services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  web:
    build: .
    command: uvicorn fitcv_cp.main:app --host 0.0.0.0 --port 8000 --reload
    ports: ["8000:8000"]
    environment:
      - GCP_PROJECT=${GCP_PROJECT}
      - BIGQUERY_DATASET=${BIGQUERY_DATASET:-fitcv}
      - REDIS_URL=redis://redis:6379/0
      - GOOGLE_APPLICATION_CREDENTIALS=/app/sa_key.json
    volumes:
      - .:/app
      - ${GCP_SA_KEY_PATH:-./fitcv-491123-51c030d71e07.json}:/app/sa_key.json:ro
    depends_on: [redis]

  worker:
    build: .
    command: rq worker fitcv --url redis://redis:6379/0
    environment:
      - GCP_PROJECT=${GCP_PROJECT}
      - BIGQUERY_DATASET=${BIGQUERY_DATASET:-fitcv}
      - REDIS_URL=redis://redis:6379/0
      - GOOGLE_APPLICATION_CREDENTIALS=/app/sa_key.json
    volumes:
      - .:/app
      - ${GCP_SA_KEY_PATH:-./fitcv-491123-51c030d71e07.json}:/app/sa_key.json:ro
    depends_on: [redis]
