- generic [ref=f5e2]:
  - complementary "Primary navigation" [ref=f5e3]:
    - link "FitCV Control Plane Local workspace" [ref=f5e4] [cursor=pointer]:
      - /url: /admin/settings
      - generic [ref=f5e9]:
        - strong [ref=f5e10]: FitCV Control Plane
        - generic [ref=f5e11]: Local workspace
    - navigation "Workspace" [ref=f5e12]:
      - link "Runs" [ref=f5e13] [cursor=pointer]:
        - /url: /admin/runs
      - link "Scans" [ref=f5e16] [cursor=pointer]:
        - /url: /admin/scans
      - link "Candidate Profiles" [ref=f5e20] [cursor=pointer]:
        - /url: /admin/candidate-profiles
      - link "Bookmarks" [ref=f5e24] [cursor=pointer]:
        - /url: /admin/bookmarks
      - link "Synonyms" [ref=f5e27] [cursor=pointer]:
        - /url: /admin/synonyms
      - group [ref=f5e31]:
        - generic "Pipeline ›" [ref=f5e32] [cursor=pointer]
        - generic [ref=f5e35]:
          - link "Overview" [ref=f5e36] [cursor=pointer]:
            - /url: /admin/settings
          - link "Enrichment" [ref=f5e37] [cursor=pointer]:
            - /url: /admin/settings/enrichment
          - link "Screening" [ref=f5e38] [cursor=pointer]:
            - /url: /admin/settings/screening
          - link "Shortlisting" [ref=f5e39] [cursor=pointer]:
            - /url: /admin/settings/shortlisting
          - link "Ranking" [ref=f5e40] [cursor=pointer]:
            - /url: /admin/settings/ranking
          - link "Preference Optimization" [ref=f5e41] [cursor=pointer]:
            - /url: /admin/optimization
          - link "CV Analysis" [ref=f5e42] [cursor=pointer]:
            - /url: /admin/settings/cv-analysis
          - link "CV Generation" [ref=f5e43] [cursor=pointer]:
            - /url: /admin/settings/cv-generation
          - link "Runtime & Limits" [ref=f5e44] [cursor=pointer]:
            - /url: /admin/settings/runtime-limits
          - link "Automation & Reuse" [ref=f5e45] [cursor=pointer]:
            - /url: /admin/settings/automation-reuse
          - link "Prompt Management" [ref=f5e46] [cursor=pointer]:
            - /url: /admin/settings/prompt-management
      - group [ref=f5e47]:
        - generic "Application ›" [ref=f5e48] [cursor=pointer]
        - generic [ref=f5e52]:
          - link "API Providers" [ref=f5e53] [cursor=pointer]:
            - /url: /admin/api-providers
          - link "LLM Configuration" [ref=f5e54] [cursor=pointer]:
            - /url: /admin/llm-configuration
          - link "System" [ref=f5e55] [cursor=pointer]:
            - /url: /admin/system
          - link "Lifecycle" [ref=f5e56] [cursor=pointer]:
            - /url: /admin/lifecycle
  - generic [ref=f5e57]:
    - banner [ref=f5e58]:
      - generic [ref=f5e62]:
        - heading "System" [level=1] [ref=f5e63]
        - paragraph [ref=f5e64]: Backup, restore, retry, and worker recovery settings.
      - generic [ref=f5e65]:
        - button "Switch to light theme" [ref=f5e66] [cursor=pointer]:
          - generic [ref=f5e70]: Light
        - button "Shutdown FitCV" [ref=f5e71] [cursor=pointer]
    - main [ref=f5e76]:
      - generic [ref=f5e78]:
        - heading "System" [level=1] [ref=f5e79]
        - paragraph [ref=f5e80]: Backup, restore, retry, and worker recovery settings.
      - generic [ref=f5e81]:
        - heading "Data and Backup" [level=2] [ref=f5e82]
        - generic [ref=f5e83]:
          - generic [ref=f5e84]: Database location
          - code [ref=f5e86]: C:\tmp\fitcv-settings-local-audit-6258c9d459124f8ea99cea1106e21770\AppData\Local\FitCV\data\fitcv.sqlite3
          - generic [ref=f5e87]: Database integrity
          - generic [ref=f5e88]: ok
          - generic [ref=f5e89]: Database size
          - generic [ref=f5e90]: 491520 bytes
          - generic [ref=f5e91]: Last backup
          - generic [ref=f5e92]: No backup yet
        - button "Download Backup" [ref=f5e95] [cursor=pointer]
        - generic [ref=f5e96]:
          - generic [ref=f5e97]:
            - text: Backup archive
            - button "Backup archive" [ref=f5e98]
          - generic [ref=f5e99]:
            - text: Destination data folder
            - textbox "Destination data folder" [ref=f5e100]
          - button "Import Backup" [ref=f5e101] [cursor=pointer]
      - generic [ref=f5e102]:
        - generic [ref=f5e103]:
          - heading "Request Retry" [level=2] [ref=f5e104]
          - generic [ref=f5e105]:
            - generic [ref=f5e106]:
              - text: Maximum Attempts
              - spinbutton "Maximum Attempts Includes the initial attempt. Set to 1 for no retry." [ref=f5e107]: "3"
              - generic [ref=f5e108]: Includes the initial attempt. Set to 1 for no retry.
            - generic [ref=f5e109]:
              - text: Initial Backoff (seconds)
              - spinbutton "Initial Backoff (seconds) Fixed wait before every retry." [ref=f5e110]: "10"
              - generic [ref=f5e111]: Fixed wait before every retry.
            - generic [ref=f5e112]:
              - text: Error Detail Limit
              - spinbutton "Error Detail Limit" [ref=f5e113]: "10000"
        - generic [ref=f5e114]:
          - heading "Worker Recovery" [level=2] [ref=f5e115]
          - generic [ref=f5e116]:
            - generic [ref=f5e117]:
              - text: Lease (seconds)
              - spinbutton "Lease (seconds)" [ref=f5e118]: "300"
            - generic [ref=f5e119]:
              - text: Reconciler Interval (seconds)
              - spinbutton "Reconciler Interval (seconds)" [ref=f5e120]: "30"
          - button "Save System Settings" [ref=f5e121] [cursor=pointer]