import { PipelineSectionDef } from "./types";

export const PIPELINE_SECTIONS: PipelineSectionDef[] = [
  {
    id: "overview",
    title: "Pipeline Overview",
    description: "Set the most important pipeline volumes and output limits. Changes apply to future runs.",
    ownedKeys: [
      "pipeline.vector_search_top_n",
      "pipeline.ai_score_top_n",
      "pipeline.final_top_n",
      "pipeline.evidence_top_k",
      "global_job_filters.applications_count_max",
      "global_job_filters.max_age_days",
    ],
    groups: [
      {
        title: "Candidate Scope",
        fields: [
          {
            key: "pipeline.vector_search_top_n",
            label: "Initial Candidate Pool Size",
            description: "Listings collected before shortlisting begins.",
            type: "number",
            min: 1,
            max: 1000,
            step: 1,
            defaultValue: 50,
          },
          {
            key: "pipeline.ai_score_top_n",
            label: "AI Reranking Pool Size",
            description: "Top screened listings sent for deeper AI ranking.",
            type: "number",
            min: 1,
            max: 500,
            step: 1,
            defaultValue: 50,
          },
          {
            key: "pipeline.final_top_n",
            label: "Final Output Count",
            description: "Best-fit listings returned when the pipeline finishes.",
            type: "number",
            min: 1,
            max: 100,
            step: 1,
            defaultValue: 15,
          },
          {
            key: "pipeline.evidence_top_k",
            label: "Final Evidence Items Per Job",
            description: "Strongest CV evidence items retained for each final job.",
            type: "number",
            min: 1,
            max: 20,
            step: 1,
            defaultValue: 5,
          },
        ],
      },
      {
        title: "Pre-enrichment Filter",
        fields: [
          {
            key: "global_job_filters.applications_count_max",
            label: "Maximum Applications",
            description: "Skip listings whose visible application count is above this limit.",
            type: "number",
            min: 1,
            max: 10000,
            step: 1,
            defaultValue: 200,
          },
          {
            key: "global_job_filters.max_age_days",
            label: "Maximum Posting Age",
            description: "Only include listings posted within this many days.",
            type: "number",
            min: 1,
            max: 365,
            step: 1,
            defaultValue: 30,
          },
        ],
      },
    ],
  },
  {
    id: "enrichment",
    title: "Enrichment",
    description: "Control how listing information is prepared before screening.",
    ownedKeys: [
      "global_job_filters.applications_count_max",
      "global_job_filters.max_age_days",
    ],
    groups: [
      {
        title: "Pre-enrichment Filter",
        fields: [
          {
            key: "global_job_filters.applications_count_max",
            label: "Maximum Applications",
            description: "Skip listings whose visible application count is above this limit.",
            type: "number",
            min: 1,
            max: 10000,
            step: 1,
            defaultValue: 200,
          },
          {
            key: "global_job_filters.max_age_days",
            label: "Maximum Posting Age",
            description: "Only include listings posted within this many days.",
            type: "number",
            min: 1,
            max: 365,
            step: 1,
            defaultValue: 30,
          },
        ],
      },
    ],
  },
  {
    id: "screening",
    title: "Screening",
    description: "Choose which listings qualify before ranking.",
    ownedKeys: ["rule_filter.selected_filters"],
    groups: [
      {
        title: "Fit Context",
        fields: [
          {
            key: "rule_filter.selected_filters",
            member: "missing_fit_context",
            label: "Require Fit Context",
            description: "Continue only when the listing has enough role context for a reliable fit decision.",
            type: "membership",
            defaultValue: true,
          },
        ],
      },
      {
        title: "Preferences",
        fields: [
          {
            key: "rule_filter.selected_filters",
            member: "location_type_excluded",
            label: "Location & Work Mode",
            description: "Apply selected location and remote-work exclusions.",
            type: "membership",
            defaultValue: true,
          },
          {
            key: "rule_filter.selected_filters",
            member: "seniority_mismatch",
            label: "Seniority Preference",
            description: "Exclude roles clearly outside the target seniority.",
            type: "membership",
            defaultValue: true,
          },
          {
            key: "rule_filter.selected_filters",
            member: "contract_type_excluded",
            label: "Contract Preference",
            description: "Exclude contract types outside declared preferences.",
            type: "membership",
            defaultValue: true,
          },
          {
            key: "rule_filter.selected_filters",
            member: "experience_level_excluded",
            label: "Experience Preference",
            description: "Exclude roles clearly outside the target experience level.",
            type: "membership",
            defaultValue: true,
          },
        ],
      },
    ],
  },
  {
    id: "shortlisting",
    title: "Shortlisting",
    description: "Control how many shortlisted listings continue to ranking.",
    ownedKeys: ["pipeline.vector_search_top_n"],
    groups: [
      {
        title: "Candidate Scope",
        fields: [
          {
            key: "pipeline.vector_search_top_n",
            label: "Initial Candidate Pool Size",
            description: "Listings collected before shortlisting begins.",
            type: "number",
            min: 1,
            max: 1000,
            step: 1,
            defaultValue: 50,
          },
        ],
      },
    ],
  },
  {
    id: "ranking",
    title: "Ranking",
    description: "Control how shortlisted listings receive their final fit score.",
    ownedKeys: [
      "pipeline.ai_score_top_n",
      "pipeline.final_top_n",
      "ranking_policy.structured_factor_weights.must_have_match",
      "ranking_policy.structured_factor_weights.title_relevance",
      "ranking_policy.structured_factor_weights.seniority_fit",
      "ranking_policy.structured_factor_weights.declared_preference_fit",
      "ranking_policy.structured_factor_weights.location_fit",
      "ranking_policy.structured_factor_weights.language_fit",
      "ranking_policy.declared_preference_component_weights.domain",
      "ranking_policy.declared_preference_component_weights.role_family",
      "ranking_policy.declared_preference_component_weights.work_mode",
      "ranking_policy.fit_label_thresholds.strong",
      "ranking_policy.fit_label_thresholds.stretch",
    ],
    groups: [
      {
        title: "Candidate Scope",
        fields: [
          {
            key: "pipeline.ai_score_top_n",
            label: "AI Reranking Pool Size",
            description: "Top screened listings sent for deeper AI ranking.",
            type: "number",
            min: 1,
            max: 500,
            step: 1,
            defaultValue: 50,
          },
          {
            key: "pipeline.final_top_n",
            label: "Final Output Count",
            description: "Best-fit listings returned when the pipeline finishes.",
            type: "number",
            min: 1,
            max: 100,
            step: 1,
            defaultValue: 15,
          },
        ],
      },
      {
        title: "Factor Weights",
        description: "Set each factor share of the final ranking score.",
        fields: [
          {
            key: "ranking_policy.structured_factor_weights.must_have_match",
            label: "Must-have Match",
            description: "Required skills and qualifications. Missing essentials reduce the final score.",
            type: "number",
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.3,
          },
          {
            key: "ranking_policy.structured_factor_weights.title_relevance",
            label: "Title Relevance",
            description: "Similarity between target and listing titles.",
            type: "number",
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.2,
          },
          {
            key: "ranking_policy.structured_factor_weights.seniority_fit",
            label: "Seniority Fit",
            description: "Alignment with target career level.",
            type: "number",
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.15,
          },
          {
            key: "ranking_policy.structured_factor_weights.declared_preference_fit",
            label: "Preference Fit",
            description: "Declared domain, role family, and work-mode preferences.",
            type: "number",
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.15,
          },
          {
            key: "ranking_policy.structured_factor_weights.location_fit",
            label: "Location Fit",
            description: "Alignment with preferred locations.",
            type: "number",
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.1,
          },
          {
            key: "ranking_policy.structured_factor_weights.language_fit",
            label: "Language Fit",
            description: "Alignment with required and preferred languages.",
            type: "number",
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.1,
          },
        ],
      },
      {
        title: "Preference Fit Balance",
        description: "Choose which declared preferences shape the Preference Fit factor.",
        fields: [
          {
            key: "ranking_policy.declared_preference_component_weights.domain",
            label: "Domain Preference",
            description: "Higher values favor jobs in declared industries and domains.",
            type: "number",
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.5,
          },
          {
            key: "ranking_policy.declared_preference_component_weights.role_family",
            label: "Role Family Preference",
            description: "Higher values favor jobs in declared role families.",
            type: "number",
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.3,
          },
          {
            key: "ranking_policy.declared_preference_component_weights.work_mode",
            label: "Work Mode Preference",
            description: "Higher values favor declared remote, hybrid, or onsite preferences.",
            type: "number",
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.2,
          },
        ],
      },
      {
        title: "Fit Labels",
        fields: [
          {
            key: "ranking_policy.fit_label_thresholds.strong",
            label: "Strong Fit Threshold",
            description: "Minimum score needed before a listing is labeled Strong Fit.",
            type: "number",
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.7,
          },
          {
            key: "ranking_policy.fit_label_thresholds.stretch",
            label: "Stretch Fit Threshold",
            description: "Minimum score needed before a listing is labeled Stretch Fit.",
            type: "number",
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.4,
          },
        ],
      },
    ],
  },
  {
    id: "cv-analysis",
    title: "CV Analysis",
    description: "Control how CV evidence is compared with each job.",
    ownedKeys: [
      "pipeline.evidence_top_k",
      "cv_analysis.semantic_alignment.enabled",
      "cv_analysis.semantic_alignment.required_skill_lexical_weight",
      "cv_analysis.semantic_alignment.required_skill_semantic_weight",
      "cv_analysis.semantic_alignment.role_lexical_weight",
      "cv_analysis.semantic_alignment.role_semantic_weight",
      "cv_analysis.semantic_alignment.responsibility_lexical_weight",
      "cv_analysis.semantic_alignment.responsibility_semantic_weight",
      "cv_analysis.semantic_alignment.domain_lexical_weight",
      "cv_analysis.semantic_alignment.domain_semantic_weight",
    ],
    groups: [
      {
        title: "Evidence Scope",
        fields: [
          {
            key: "pipeline.evidence_top_k",
            label: "Final Evidence Items Per Job",
            description: "Strongest CV evidence items retained for each final job.",
            type: "number",
            min: 1,
            max: 20,
            step: 1,
            defaultValue: 5,
          },
        ],
      },
      {
        title: "Semantic Alignment",
        fields: [
          {
            key: "cv_analysis.semantic_alignment.enabled",
            label: "Semantic Alignment",
            description: "Compare meaning as well as exact words so equivalent experience can match differently phrased job requirements.",
            type: "boolean",
            defaultValue: true,
          },
          {
            key: "cv_analysis.semantic_alignment.model",
            label: "Embedding Model",
            description: "Model used to compare meaning when Semantic Alignment is on.",
            type: "readonly",
            defaultValue: "text-embedding-005",
            readonlyValue: "text-embedding-005",
          },
        ],
      },
      {
        title: "Match Methods",
        description: "Balance exact wording against meaning-based similarity for key job areas.",
        fields: [
          {
            key: "cv_analysis.semantic_alignment.required_skill_lexical_weight",
            label: "Skills Match — Exact Wording",
            description: "Higher values reward direct phrase matches in skills and capability evidence.",
            type: "number",
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.7,
          },
          {
            key: "cv_analysis.semantic_alignment.required_skill_semantic_weight",
            label: "Skills Match — Semantic Similarity",
            description: "Higher values reward equivalent meaning even when skills use different wording.",
            type: "number",
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.3,
          },
          {
            key: "cv_analysis.semantic_alignment.role_lexical_weight",
            label: "Role Match — Exact Wording",
            description: "Higher values reward direct phrase matches in role titles.",
            type: "number",
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.6,
          },
          {
            key: "cv_analysis.semantic_alignment.role_semantic_weight",
            label: "Role Match — Semantic Similarity",
            description: "Higher values reward equivalent meaning in role expectations.",
            type: "number",
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.4,
          },
          {
            key: "cv_analysis.semantic_alignment.responsibility_lexical_weight",
            label: "Responsibilities Match — Exact Wording",
            description: "Higher values reward direct phrase matches in responsibilities.",
            type: "number",
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.25,
          },
          {
            key: "cv_analysis.semantic_alignment.responsibility_semantic_weight",
            label: "Responsibilities Match — Semantic Similarity",
            description: "Higher values reward equivalent meaning in achievements.",
            type: "number",
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.75,
          },
          {
            key: "cv_analysis.semantic_alignment.domain_lexical_weight",
            label: "Domain Match — Exact Wording",
            description: "Higher values reward direct phrase matches in industry domain.",
            type: "number",
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.4,
          },
          {
            key: "cv_analysis.semantic_alignment.domain_semantic_weight",
            label: "Domain Match — Semantic Similarity",
            description: "Higher values reward equivalent meaning in domain experience.",
            type: "number",
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.6,
          },
        ],
      },
    ],
  },
  {
    id: "cv-generation",
    title: "CV Generation",
    description: "Choose content included in generated CVs.",
    ownedKeys: [
      "cv_summary_enabled",
      "cv_education_enabled",
      "cv_experience_enabled",
      "cv_skills_enabled",
      "cv_certifications_enabled",
      "cv_projects_enabled",
      "cv_publications_enabled",
      "cv_languages_enabled",
    ],
    groups: [
      {
        title: "Included Sections",
        description: "Choose which CV sections are included in generated CV output.",
        fields: [
          {
            key: "cv_summary_enabled",
            label: "Summary",
            description: "Include professional summary.",
            type: "boolean",
            defaultValue: true,
          },
          {
            key: "cv_education_enabled",
            label: "Education",
            description: "Include education history.",
            type: "boolean",
            defaultValue: true,
          },
          {
            key: "cv_experience_enabled",
            label: "Experience",
            description: "Include work experience.",
            type: "boolean",
            defaultValue: true,
          },
          {
            key: "cv_skills_enabled",
            label: "Skills",
            description: "Include skills section.",
            type: "boolean",
            defaultValue: true,
          },
          {
            key: "cv_certifications_enabled",
            label: "Certifications",
            description: "Include certifications.",
            type: "boolean",
            defaultValue: true,
          },
          {
            key: "cv_projects_enabled",
            label: "Projects",
            description: "Include relevant projects.",
            type: "boolean",
            defaultValue: true,
          },
          {
            key: "cv_publications_enabled",
            label: "Publications",
            description: "Include publications when available.",
            type: "boolean",
            defaultValue: false,
          },
          {
            key: "cv_languages_enabled",
            label: "Languages",
            description: "Include language proficiency.",
            type: "boolean",
            defaultValue: true,
          },
        ],
      },
    ],
  },
  {
    id: "runtime-limits",
    title: "Runtime & Limits",
    description: "Set shared provider request pacing and maximum simultaneous jobs.",
    ownedKeys: [
      "llm_runtime.request_start_interval_secs",
      "stage_runtime.enrich.concurrency",
      "stage_runtime.ranking.concurrency",
      "stage_runtime.cv_analysis.concurrency",
      "stage_runtime.cv_generation.concurrency",
    ],
    groups: [
      {
        title: "Provider Request Pacing",
        fields: [
          {
            key: "llm_runtime.request_start_interval_secs",
            label: "Minimum Request Start Interval (seconds)",
            description: "Minimum time between generative request starts for the same provider connection. Providers are paced independently. Zero disables pacing; retry backoff remains separate.",
            type: "number",
            min: 0,
            max: 3600,
            step: 0.1,
            defaultValue: 0,
          },
        ],
      },
      {
        title: "Stage Concurrency",
        description: "Set the maximum number of jobs that may run simultaneously for each pipeline stage.",
        fields: [
          {
            key: "stage_runtime.enrich.concurrency",
            label: "Enrichment",
            description: "Set the maximum simultaneous Enrichment jobs.",
            type: "number",
            min: 1,
            step: 1,
            defaultValue: 8,
          },
          {
            key: "stage_runtime.ranking.concurrency",
            label: "Ranking",
            description: "Set the maximum simultaneous Ranking jobs.",
            type: "number",
            min: 1,
            step: 1,
            defaultValue: 4,
          },
          {
            key: "stage_runtime.cv_analysis.concurrency",
            label: "CV Analysis",
            description: "Set the maximum simultaneous local CV Analysis jobs.",
            type: "number",
            min: 1,
            step: 1,
            defaultValue: 4,
          },
          {
            key: "stage_runtime.cv_generation.concurrency",
            label: "CV Generation",
            description: "Set the maximum simultaneous CV Generation jobs.",
            type: "number",
            min: 1,
            step: 1,
            defaultValue: 4,
          },
        ],
      },
    ],
  },
  {
    id: "automation-reuse",
    title: "Automation & Reuse",
    description: "Control reuse of previous pipeline outputs and automation of shared synonym mappings.",
    ownedKeys: [
      "reuse.enrich.enabled",
      "reuse.ranking.enabled",
      "reuse.cv_analysis.enabled",
      "reuse.cv_generation.enabled",
      "reuse.synonym_triage.enabled",
      "synonym_management.propose_enabled",
      "synonym_management.auto_accept_suggestions_enabled",
      "synonym_management.apply_approved_enabled",
    ],
    groups: [
      {
        title: "Reuse Results",
        description: "Reuse matching output from earlier completed runs.",
        fields: [
          {
            key: "reuse.enrich.enabled",
            label: "Reuse Enrichment Results",
            description: "Reuse matching enrichment output from an earlier run.",
            type: "boolean",
            defaultValue: true,
          },
          {
            key: "reuse.ranking.enabled",
            label: "Reuse Ranking Results",
            description: "Reuse matching ranking output from an earlier run.",
            type: "boolean",
            defaultValue: true,
          },
          {
            key: "reuse.cv_analysis.enabled",
            label: "Reuse CV Analysis Results",
            description: "Reuse matching CV analysis output from an earlier run.",
            type: "boolean",
            defaultValue: true,
          },
          {
            key: "reuse.cv_generation.enabled",
            label: "Reuse Generated CVs",
            description: "Reuse matching generated CV output from an earlier run.",
            type: "boolean",
            defaultValue: true,
          },
          {
            key: "reuse.synonym_triage.enabled",
            label: "Reuse Synonym Proposal Analysis",
            description: "Reuse equivalent proposal-generation analysis from an earlier run. Review decisions remain central.",
            type: "boolean",
            defaultValue: true,
          },
        ],
      },
      {
        title: "Synonym Automation",
        description: "Automate generation and application of shared synonyms.",
        fields: [
          {
            key: "synonym_management.propose_enabled",
            label: "Generate Synonym Proposals",
            description: "Suggest alternate terms when different wording may represent the same skill, role, or domain.",
            type: "boolean",
            defaultValue: true,
          },
          {
            key: "synonym_management.auto_accept_suggestions_enabled",
            label: "Auto-accept Synonym Suggestions",
            description: "Automatically accept conflict-free suggestions. When off, every suggestion enters the review queue as Pending.",
            type: "boolean",
            defaultValue: false,
          },
          {
            key: "synonym_management.apply_approved_enabled",
            label: "Apply Approved Synonyms",
            description: "Use approved shared synonym mappings in current and future pipeline runs.",
            type: "boolean",
            defaultValue: true,
          },
        ],
      },
    ],
  },
];

export function buildFallbackDefaults(): Record<string, any> {
  const defaults: Record<string, any> = {
    "rule_filter.selected_filters": [
      "seniority_mismatch",
      "missing_fit_context",
      "location_type_excluded",
      "contract_type_excluded",
      "experience_level_excluded",
    ],
  };
  for (const section of PIPELINE_SECTIONS) {
    for (const group of section.groups) {
      for (const field of group.fields) {
        if (field.type !== "membership" && field.defaultValue !== undefined) {
          defaults[field.key] = field.defaultValue;
        }
      }
    }
  }
  return defaults;
}
