from pathlib import Path
import re

partial = Path('src/fitcv_cp/templates/_synonym_decision_ledger.html')
partial.write_text("""<div class=\"card\">\n  <h3 style=\"margin:0 0 0.15rem\">Synonym Decisions</h3>\n  <div class=\"meta\" style=\"margin:0 0 0.35rem\">Decision = current state. Recommendation = model suggestion. Queue Source = provenance only.</div>\n  <div style=\"overflow:auto;max-height:14rem;border:1px solid var(--accent);border-radius:6px\">\n    <table style=\"width:100%;border-collapse:collapse;font-size:0.82rem\">\n      <thead>\n        <tr style=\"background:var(--panel-bg)\">\n          <th style=\"text-align:left;padding:0.35rem 0.5rem\">Alias</th>\n          <th style=\"text-align:left;padding:0.35rem 0.5rem\">Canonical</th>\n          <th style=\"text-align:left;padding:0.35rem 0.5rem\">Decision</th>\n          <th style=\"text-align:left;padding:0.35rem 0.5rem\">Recommendation</th>\n          <th style=\"text-align:left;padding:0.35rem 0.5rem\">Queue Source</th>\n          <th style=\"text-align:left;padding:0.35rem 0.5rem\">Last Action / Why</th>\n        </tr>\n      </thead>\n      <tbody>\n        {% for row in synonym_proposal_decision_ledger %}\n        <tr>\n          <td style=\"padding:0.3rem 0.5rem\"><code>{{ row.alias }}</code></td>\n          <td style=\"padding:0.3rem 0.5rem\"><code>{{ row.canonical }}</code></td>\n          <td style=\"padding:0.3rem 0.5rem\">\n            <span class=\"badge badge-{{ 'warning' if row.decision == 'pending' else ('success' if row.decision == 'approve' else ('error' if row.decision == 'reject' else ('info' if row.decision == 'defer' else 'neutral'))) }}\">{{ row.decision_display or row.decision or '—' }}</span>\n            {% if row.is_overridden %}<span class=\"badge badge-info\" style=\"margin-left:0.25rem\">Overridden</span>{% endif %}\n          </td>\n          <td style=\"padding:0.3rem 0.5rem\">{% if row.recommendation_display and row.recommendation_display != '—' %}<span class=\"badge badge-neutral\">{{ row.recommendation_display }}</span>{% else %}—{% endif %}</td>\n          <td style=\"padding:0.3rem 0.5rem\">{{ row.decision_source_display or row.decision_source }}</td>\n          <td style=\"padding:0.3rem 0.5rem\">\n            <div>{{ row.last_action_display or '—' }}</div>\n            <div class=\"meta\">{{ row.decision_reason_display or row.decision_reason }}</div>\n          </td>\n        </tr>\n        {% endfor %}\n      </tbody>\n    </table>\n  </div>\n</div>\n""", encoding='utf-8')

for path in ['src/fitcv_cp/templates/run_detail.html', 'src/fitcv_cp/templates/synonym_review.html']:
    p = Path(path)
    text = p.read_text(encoding='utf-8')
    pattern = re.compile(r'(?s)\{%-? if synonym_proposal_decision_ledger %-?\}\s*<div class="card">.*?<\/div>\s*\{%-? else %-?\}')
    replacement = '{% if synonym_proposal_decision_ledger %}\n  {% include "_synonym_decision_ledger.html" %}\n  {% else %}'
    if not pattern.search(text):
        raise SystemExit(f'ledger block not found in {path}')
    text = pattern.sub(replacement, text, count=1)
    p.write_text(text, encoding='utf-8')
    print(f'patched {path}')

p = Path('src/fitcv_cp/templates/run_detail.html')
text = p.read_text(encoding='utf-8')
text = text.replace('<button class="tab-btn active" id="tab-btn-enriched"   onclick="showTab(\'enriched\')">📊 Enriched Jobs</button>', '<button class="tab-btn active" id="tab-btn-enriched" role="tab" aria-selected="true" aria-controls="pane-enriched" onclick="showTab(\'enriched\')">📊 Enriched Jobs</button>')
text = text.replace('<button class="tab-btn"        id="tab-btn-jobs-input" onclick="showTab(\'jobs-input\')">📄 Original Job Input</button>', '<button class="tab-btn"        id="tab-btn-jobs-input" role="tab" aria-selected="false" aria-controls="pane-jobs-input" onclick="showTab(\'jobs-input\')">📄 Original Job Input</button>')
text = text.replace('<button class="tab-btn"        id="tab-btn-profile"    onclick="showTab(\'profile\')">👤 Candidate Profile</button>', '<button class="tab-btn"        id="tab-btn-profile"    role="tab" aria-selected="false" aria-controls="pane-profile" onclick="showTab(\'profile\')">👤 Candidate Profile</button>')
text = text.replace('<div class="pane-container tab-pane active" id="pane-enriched" data-tab-id="enriched" data-tab-url="/admin/runs/{{ run.run_id }}/tabs/enriched">', '<div class="pane-container tab-pane active" id="pane-enriched" role="tabpanel" aria-labelledby="tab-btn-enriched" data-tab-id="enriched" data-tab-url="/admin/runs/{{ run.run_id }}/tabs/enriched">')
text = text.replace('<div class="pane-container tab-pane" id="pane-jobs-input" data-tab-id="jobs-input" data-tab-url="/admin/runs/{{ run.run_id }}/tabs/jobs-input">', '<div class="pane-container tab-pane" id="pane-jobs-input" role="tabpanel" aria-labelledby="tab-btn-jobs-input" data-tab-id="jobs-input" data-tab-url="/admin/runs/{{ run.run_id }}/tabs/jobs-input">')
text = text.replace('<div class="pane-container tab-pane" id="pane-profile" data-tab-id="profile" data-tab-url="/admin/runs/{{ run.run_id }}/tabs/profile">', '<div class="pane-container tab-pane" id="pane-profile" role="tabpanel" aria-labelledby="tab-btn-profile" data-tab-id="profile" data-tab-url="/admin/runs/{{ run.run_id }}/tabs/profile">')
text = text.replace("  document.querySelectorAll('.tab-pane').forEach(p => {\n    p.style.display = 'none';\n    p.classList.remove('active');\n  });\n  document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));\n  const pane = document.getElementById('pane-' + id);\n  pane.style.display = 'block';\n  pane.classList.add('active');\n  document.getElementById('tab-btn-' + id).classList.add('active');", "  document.querySelectorAll('.tab-pane').forEach(p => {\n    p.style.display = 'none';\n    p.classList.remove('active');\n    p.hidden = true;\n  });\n  document.querySelectorAll('.tab-btn').forEach(b => {\n    b.classList.remove('active');\n    b.setAttribute('aria-selected', 'false');\n  });\n  const pane = document.getElementById('pane-' + id);\n  pane.style.display = 'block';\n  pane.classList.add('active');\n  pane.hidden = false;\n  const button = document.getElementById('tab-btn-' + id);\n  button.classList.add('active');\n  button.setAttribute('aria-selected', 'true');")
p.write_text(text, encoding='utf-8')
print('patched run_detail tabs')
